name=input("Enter Emp Name :")
empid=int(input("Enter Emp Id :"))
empdesig=input("Enter Designation :")
empdoj=input("Enter DOJ mm/dd/yyyy:")
empsal=float(input("Enter the salary :"))

print("#"*40)
print("Employee Profile")
print("#"*40)
print("Employee ID",empid)
print("Employee Name",name)
print("Employee Designation",empdesig)
print("Employee Date of Joining",empdoj)
print("Employee Salary",empsal )